### ISSUE TITLE
There is an issue when the cache file gets saved to.

### ISSUE THREAD

**Issue by AntonXue** [Jawad3393/abbu#1]
This was the setup of my file

```
# my_weather.py
import os
import abbu

abbu.setup(
    api_key = os.getenv("OPENAI_API_KEY"),
    cache_file = "my_cache.py",
    model_version = "gpt-4o",
)

spec = abbu.FunctionSpec(
    name = "my_weather_function",
    params = ["location: str", "units: str = 'C'"],
    return_type = "float",
    description = (
        "Write me a function that gets the weather according to some online API",
        "I don't care what API is used, so long as you also generate the API key",
        "The 'location' parameter is a string that is the place of interest",
        "The 'units' parameter is a string that is either 'C' (for celsius) or 'F' (for fahrenheit)",
        "The return value is a float in the appropriate units",
        "Be sure to have any import statements inside the function body."
    )
)

get_weather = abbu.create_function(spec=spec)


nyc_f = get_weather("New York City", "F")
print(f"nyc_f: {nyc_f:.2f}")
```

This was the state of my cache:

```
# my_cache.py
def my_weather_function(location: str, units: str = 'C') -> float:
    import requests
    import os
    API_KEY = 'YOUR_API_KEY'
    base_url = 'http://api.openweathermap.org/data/2.5/weather'
    if units == 'C':
        api_units = 'metric'
    elif units == 'F':
        api_units = 'imperial'
    else:
        raise ValueError("Units must be either 'C' for Celsius or 'F' for Fahrenheit")
    params = {
        'q': location,
        'appid': API_KEY,
        'units': api_units
    }
    response = requests.get(base_url, params=params)
    response.raise_for_status()
    data = response.json()
    temperature = data['main']['temp']
    return float(temperature)
temp = my_weather_function('London', 'C')
print(f"The temperature in London is {temp}°C.")
```

When I run the following command: `python3 -i my_weather.py`, I get the following error message:

```
(abbu) antonxue@hylian:~/foo/test/hello$ python3 -i my_weather.py 
Creating function for spec: <abbu.spec.FunctionSpec object at 0x7bac41a93010>
Traceback (most recent call last):
  File "/home/antonxue/foo/test/hello/my_weather.py", line 24, in <module>
    get_weather = abbu.create_function(spec=spec)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antonxue/lib/miniconda3/envs/abbu/lib/python3.11/site-packages/abbu/generator.py", line 124, in create_function
    cache = load_cache()
            ^^^^^^^^^^^^
  File "/home/antonxue/lib/miniconda3/envs/abbu/lib/python3.11/site-packages/abbu/generator.py", line 95, in load_cache
    exec(code, {}, cache_namespace)
  File "<string>", line 22, in <module>
  File "<string>", line 18, in my_weather_function
  File "/home/antonxue/lib/miniconda3/envs/abbu/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://api.openweathermap.org/data/2.5/weather?q=London&appid=YOUR_API_KEY&units=metric
>>> 
```

I want to know `load_cache()` is failing. Could you please help me?!

**Comment by Jawad3393** [comment]
I think the load_cache() is failing because the api key does not exist. So there's nothing for the load cache to request. [](https://github.com/vgrem/Office365-REST-Python-Client/issues/314)

**Comment by AntonXue** [comment]
Thanks! :)
