### ISSUE TITLE
Nondescriptive title.

### ISSUE THREAD

**Issue by AntonXue** [Jawad3393/abbu#2]
Please help! :(

```
(abbu) antonxue@hylian:~/foo/test/hello$ python3 -i web_crawler.py 
Creating function for spec: <abbu.spec.FunctionSpec object at 0x74256d517250>
Loaded cache: {'my_weather_function': <function my_weather_function at 0x74256d520040>}
Generating code for spec: <abbu.spec.FunctionSpec object at 0x74256d517250>
Traceback (most recent call last):
  File "/home/antonxue/foo/test/hello/web_crawler.py", line 24, in <module>
    crawler_func = abbu.create_function(spec=spec)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antonxue/lib/miniconda3/envs/abbu/lib/python3.11/site-packages/abbu/generator.py", line 141, in create_function
    save_cache(cache)
  File "/home/antonxue/lib/miniconda3/envs/abbu/lib/python3.11/site-packages/abbu/generator.py", line 109, in save_cache
    file.write(func_code + "\n\n")
               ~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'function' and 'str'
```

**Comment by Jawad3393** [comment]
This was fixed using 
`if isinstance(func_code, str):
                file.write(func_code + "\n\n")`
